### ISSUE TITLE
Would you upload the original RGB-D data of the demo？

### ISSUE THREAD

**Issue by xfliu1998** [changhaonan/Mono-STAR-demo#2]

**Comment by changhaonan** [comment]
Of course. You can download the data at [https://drive.google.com/drive/folders/14h41e_sB8EmFnZuMHNBHrG4ieGtURtQE?usp=sharing](https://drive.google.com/drive/folders/14h41e_sB8EmFnZuMHNBHrG4ieGtURtQE?usp=sharing)

**Comment by xfliu1998** [comment]
Thank you very much.
